### ISSUE TITLE
completely lost wifi after installing this patch

### ISSUE THREAD

**Issue by cil8** [longsleep/bcmwl-ubuntu#11] opened 2015-09-16 08:32 UTC
Hi.

I'm running Ubuntu 15.04 on XPS13 2015. I landed on your page from https://wiki.ubuntu.com/Dell%20XPS%202015

I just installed the patch following your instructions, while running kernel 4.2. No problems whatsoever while building and installing the .deb package. After reboot, still no wifi. The bad thing is that now I'm without wifi even booting kernel 4.1.6.

Any Ideas? How can I give you more details?

Thanks.

**Comment by s7dhansh** [comment] 2015-09-16 08:45
@cil8 Can you try the install again, put the output in pastebin and post the link? I guess you missed the failures like 'Error!....' that are not so visible if you don't look for them.

To enable wifi 
- You can download this deb: https://www.dropbox.com/s/ahin3nc9qezt9wz/bcmwl-kernel-source_6.30.223.248%2Bbdcom-1longsleep1_amd64.deb?dl=0 - this is what I use, with the license changed to GPl, and a null pointer patch applied, over and above with longsleep's linux-4.2 branch.
- OR, you can use the bcmwl-kernel-source provided by wily or longsleep ppa with 4.1 kernels.

**Comment by cil8** [comment] 2015-09-16 09:12
I'm sorry, you're right. I missed the GPL-incompatible error. I wasn't paying attention.

I would like to build by myself the correct package. Could you tell me where I can find instructions?

**Comment by s7dhansh** [comment] 2015-09-16 09:16
https://github.com/longsleep/bcmwl-ubuntu/issues/10

## 

Sudhanshu

**Comment by longsleep** [comment] 2015-09-16 12:35
Duplicate of #10 

Also please note that the changes for Kernel 4.2 have been merged into master and it is no longer required to use the branch.

@cil8 : Instructions how to compile are found in the README.

**Closed as completed by longsleep** 2015-09-16 12:35 UTC

**Comment by s7dhansh** [comment] 2015-09-16 16:54
@longsleep can you also add the null pointer crash fix patch in the dkms.conf?
https://launchpadlibrarian.net/196100480/0014-null-pointer-crash.patch

That resolves the kernel panic issue, at least to an extent.

**Comment by longsleep** [comment] 2015-09-17 20:33
@s7dhansh : Done, the package is now in sync with the latest Ubuntu packaging from Wily.
